# default list
defaults:
  - /habitat: habitat_config_base
  - /habitat/task: pointnav
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbd_agent
  - _self_

#overrides
habitat:
  environment:
    max_episode_steps: 500
  simulator:
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
      gpu_gpu: False
    agents:
      main_agent:
        height: 1.5
        sim_sensors:
          rgb_sensor:
            type: HabitatSimRGBSensor
            width: 256 
            height: 256
            # position:
            # - 0
            # - 1.25
            # - 0
            hfov: 90 
          depth_sensor:
            type: HabitatSimDepthSensor
            width: 256 
            height: 256 
            min_depth: 0.0
            max_depth: 10.0 
            # position:
            # - 0
            # - 1.25
            # - 0
            hfov: 90 
            normalize_depth: False
    turn_angle: 10 
    forward_step_size: 0.065

  task:
    type: Nav-v0
    lab_sensors:
      pointgoal_with_gps_compass_sensor:
        type: PointGoalWithGPSCompassSensor
        goal_format: POLAR
        dimensionality: 2
    measurements:
      distance_to_goal:
        type: DistanceToGoal
        distance_to: POINT
      success:
        type: Success
        success_distance: 0.2
      spl:
        type: SPL
    goal_sensor_uuid: pointgoal_with_gps_compass

  dataset:
    type: PointNav-v1
    split: val
    data_path: /home/hongrui/Datasets/pointnav_gibson_v1/{split}/{split}.json.gz
